# Generated by Django 4.0.5 on 2022-06-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_Field', models.CharField(max_length=100)),
                ('close_Field', models.CharField(max_length=100)),
                ('high_Field', models.CharField(max_length=100)),
                ('low_Field', models.CharField(max_length=100)),
                ('volume_Field', models.CharField(max_length=100)),
            ],
        ),
    ]
