# Generated by Django 4.0.5 on 2022-06-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeDb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getdata',
            name='close_Time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='getdata',
            name='count_Field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='getdata',
            name='open_Timee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='getdata',
            name='close_Field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='getdata',
            name='high_Field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='getdata',
            name='low_Field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='getdata',
            name='open_Field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='getdata',
            name='volume_Field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
