# Generated by Django 4.0.5 on 2022-06-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeDb', '0002_getdata_close_time_getdata_count_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='getdata',
            name='sum_Field',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
