# Generated by Django 4.0.5 on 2022-06-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeDb', '0003_getdata_sum_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getdata',
            name='count_Field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
